name: CD / CI - Integraci贸n Continua / Despliegue Continuo

on:
  push:
    branches:
      - main

jobs:
  build-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Obtener versi贸n actual
        id: get_version
        run: echo "::set-output name=version::$(npm run version --silent)"

      - name: Subir versi贸n del package.json
        run: |
          npm --no-git-tag-version version "${{ steps.get_version.outputs.version }}"
          git add package.json
          git commit -m "Subir versi贸n a ${{ steps.get_version.outputs.version }}"
          git push

